### ISSUE TITLE
Document how to use the proxy from a Proxy SDK

### ISSUE THREAD

**Issue by PEZ** [Unleash/unleash-proxy#27]
Hello again,

It is not super clear that `UNLEASH_PROXY_SECRETS` corresponds to `clientKey` when creating the client from the JavaScript Proxy SDK.

To make it easier to get started, maybe an example in the README after the list of Proxy SDKs might clarify? Or just mention that the secret should go in `clientKey`.

Or even change `clientKey` to `proxySecret`?

**Comment by killthekitten** [comment]
Second that. `clientKey` seems a much better name and sounds similar to what i.e. Sentry or Stripe would suggest using.

**Comment by ivarconr** [comment]
It makes sense. To not break existing configurations we should probably just support both in parallel (at least the env variable) but start migrating towards `CLIENT_KEYS` or `PROXY_CLIENT_KEYS` ?

**Comment by killthekitten** [comment]
@ivarconr yea, sounds like a good idea! As for the naming, I'd go either for `PROXY_CLIENT_KEYS` or `PROXY_PUBLISHABLE_KEYS`. 

Stripe calls it a "Publishable" key to distinguish from "private" keys – this way people know that it's ok to keep it in the open. It's a great developer experience because you don't have to think twice, but also that would be a non-trivial effort to introduce a new name across different Unleash packages.
